plugins {
    id 'java'
}

group = 'com.ArtemBuzEd'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.18.3'
    implementation 'com.fasterxml.jackson.core:jackson-core:2.18.3'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.18.3'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.18.3'
    implementation 'com.google.dagger:dagger:2.56'
    annotationProcessor 'com.google.dagger:dagger-compiler:2.56'
}

test {
    useJUnitPlatform()
}